import { MenuItem } from '../interfaces/menu.interface';

export const MENU_ITEMS: MenuItem[] = [
  {
    title: 'Dashboard',
    icon: 'dashboard',
    link: '/dashboard',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'Activity',
    icon: 'activity',
    link: '/activity',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'Voting',
    icon: 'voting',
    link: '/voting',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'DReps',
    icon: 'dreps',
    link: '/dreps',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'SPO',
    icon: 'spo',
    link: '/spo',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'CC',
    icon: 'cc',
    link: '/cc',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
  {
    title: 'More',
    icon: 'more',
    link: '/more',
    size: 30,
    category: 'menu',
    color: 'white',
    activeColor: '#0086AD',
  },
];
